// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://asjyrzvagvhjvnxyhpfa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFzanlyenZhZ3ZoanZueHlocGZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyMTY5MDIsImV4cCI6MjA2Njc5MjkwMn0.IxwkCHrRevrpxMV8FEPguo1kP7ZX04j1Hebf-JW4RkQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);